// Code generated by protoc-gen-go. DO NOT EDIT.
// source: groupcachepb/groupcache.proto

package groupcachepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRequest struct {
	Group                *string  `protobuf:"bytes,1,req,name=group" json:"group,omitempty"`
	Key                  *string  `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1628d0576c2b48a1, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetGroup() string {
	if m != nil && m.Group != nil {
		return *m.Group
	}
	return ""
}

func (m *GetRequest) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

type GetListRequest struct {
	Group                *string  `protobuf:"bytes,1,req,name=group" json:"group,omitempty"`
	KeyList              []string `protobuf:"bytes,2,rep,name=keyList" json:"keyList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListRequest) Reset()         { *m = GetListRequest{} }
func (m *GetListRequest) String() string { return proto.CompactTextString(m) }
func (*GetListRequest) ProtoMessage()    {}
func (*GetListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1628d0576c2b48a1, []int{1}
}

func (m *GetListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListRequest.Unmarshal(m, b)
}
func (m *GetListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListRequest.Marshal(b, m, deterministic)
}
func (m *GetListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListRequest.Merge(m, src)
}
func (m *GetListRequest) XXX_Size() int {
	return xxx_messageInfo_GetListRequest.Size(m)
}
func (m *GetListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListRequest proto.InternalMessageInfo

func (m *GetListRequest) GetGroup() string {
	if m != nil && m.Group != nil {
		return *m.Group
	}
	return ""
}

func (m *GetListRequest) GetKeyList() []string {
	if m != nil {
		return m.KeyList
	}
	return nil
}

type GetResponse struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	MinuteQps            *float64 `protobuf:"fixed64,2,opt,name=minute_qps,json=minuteQps" json:"minute_qps,omitempty"`
	Expire               *int64   `protobuf:"varint,3,opt,name=expire" json:"expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1628d0576c2b48a1, []int{2}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *GetResponse) GetMinuteQps() float64 {
	if m != nil && m.MinuteQps != nil {
		return *m.MinuteQps
	}
	return 0
}

func (m *GetResponse) GetExpire() int64 {
	if m != nil && m.Expire != nil {
		return *m.Expire
	}
	return 0
}

type GetListResponse struct {
	KvList               []*GetResponse `protobuf:"bytes,1,rep,name=kvList" json:"kvList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetListResponse) Reset()         { *m = GetListResponse{} }
func (m *GetListResponse) String() string { return proto.CompactTextString(m) }
func (*GetListResponse) ProtoMessage()    {}
func (*GetListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1628d0576c2b48a1, []int{3}
}

func (m *GetListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListResponse.Unmarshal(m, b)
}
func (m *GetListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListResponse.Marshal(b, m, deterministic)
}
func (m *GetListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListResponse.Merge(m, src)
}
func (m *GetListResponse) XXX_Size() int {
	return xxx_messageInfo_GetListResponse.Size(m)
}
func (m *GetListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListResponse proto.InternalMessageInfo

func (m *GetListResponse) GetKvList() []*GetResponse {
	if m != nil {
		return m.KvList
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "groupcachepb.GetRequest")
	proto.RegisterType((*GetListRequest)(nil), "groupcachepb.GetListRequest")
	proto.RegisterType((*GetResponse)(nil), "groupcachepb.GetResponse")
	proto.RegisterType((*GetListResponse)(nil), "groupcachepb.GetListResponse")
}

func init() {
	proto.RegisterFile("groupcachepb/groupcache.proto", fileDescriptor_1628d0576c2b48a1)
}

var fileDescriptor_1628d0576c2b48a1 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x4d, 0x83, 0x2b, 0x9d, 0x5d, 0x54, 0x82, 0xc8, 0x28, 0x2c, 0x84, 0x9c, 0x72, 0xaa,
	0xb8, 0x78, 0xf4, 0x20, 0x28, 0x14, 0xc4, 0x8b, 0x39, 0x7a, 0x91, 0x75, 0x19, 0xb4, 0x54, 0xb7,
	0xd9, 0x26, 0x59, 0xec, 0xbf, 0x97, 0xa4, 0x55, 0x7b, 0x50, 0xf6, 0x96, 0x6f, 0xe6, 0xbd, 0xc9,
	0xe3, 0xc1, 0xfc, 0xb5, 0x6d, 0x82, 0x5d, 0x2d, 0x57, 0x6f, 0x64, 0x5f, 0x2e, 0x7e, 0xa1, 0xb0,
	0x6d, 0xe3, 0x1b, 0x31, 0x1b, 0xaf, 0xd5, 0x15, 0x40, 0x49, 0xde, 0xd0, 0x26, 0x90, 0xf3, 0xe2,
	0x04, 0xf6, 0xd3, 0x16, 0x99, 0xcc, 0x74, 0x6e, 0x7a, 0x10, 0xc7, 0xc0, 0x6b, 0xea, 0x30, 0x4b,
	0xb3, 0xf8, 0x54, 0x37, 0x70, 0x58, 0x92, 0x7f, 0xa8, 0xdc, 0x0e, 0x27, 0xc2, 0x41, 0x4d, 0x5d,
	0xd4, 0x61, 0x26, 0xb9, 0xce, 0xcd, 0x37, 0xaa, 0x27, 0x98, 0xa6, 0x7f, 0x9d, 0x6d, 0xd6, 0x8e,
	0xa2, 0x7d, 0xbb, 0x7c, 0x0f, 0x84, 0x4c, 0x32, 0x3d, 0x33, 0x3d, 0x88, 0x39, 0xc0, 0x47, 0xb5,
	0x0e, 0x9e, 0x9e, 0x37, 0xd6, 0x61, 0x26, 0x99, 0x66, 0x26, 0xef, 0x27, 0x8f, 0xd6, 0x89, 0x53,
	0x98, 0xd0, 0xa7, 0xad, 0x5a, 0x42, 0x2e, 0x99, 0xe6, 0x66, 0x20, 0x75, 0x07, 0x47, 0x3f, 0xe9,
	0x86, 0xfb, 0x97, 0x30, 0xa9, 0xb7, 0x29, 0x07, 0x93, 0x5c, 0x4f, 0x17, 0x67, 0xc5, 0xb8, 0x85,
	0x62, 0x14, 0xc5, 0x0c, 0xc2, 0xc5, 0x3d, 0x40, 0x19, 0x35, 0xb7, 0x51, 0x23, 0xae, 0x81, 0x97,
	0xe4, 0x05, 0xfe, 0xe1, 0x4b, 0x05, 0x9c, 0xff, 0x7f, 0x51, 0xed, 0x7d, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x9e, 0x4c, 0xd9, 0x26, 0x93, 0x01, 0x00, 0x00,
}
